version: '3.9'

services:
  bot:
    build: .
    command: python3 main.py
    restart: always
    ports:
      - 443:443
    env_file: 
      - .env
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=${PREFIX}
    volumes:
      - ./bot:/bot