version: '3.9'

services:
  bot:
    build: .
    command: python3 main.py
    restart: always
    ports:
      - 443:443
    environment:
      - TOKEN=MTEyNzM3NzUxNjcwMTY5MjA4NQ.G56iXT.-TLOV96KYHkaz8e07q0gnfiNJPIbgBJRqO6mAk
      - PREFIX=!
      - CHANNEL_ID=1127393778328678440
    volumes:
      - ./bot:/bot